rm -rf svg
rm -rf svg_out
python3 GetFont.py 1
cp out.ttf /mnt/d/font/1_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 2
cp out.ttf /mnt/d/font/2_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 3
cp out.ttf /mnt/d/font/3_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 4
cp out.ttf /mnt/d/font/4_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 5
cp out.ttf /mnt/d/font/5_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 6
cp out.ttf /mnt/d/font/6_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 7
cp out.ttf /mnt/d/font/7_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 8
cp out.ttf /mnt/d/font/8_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 9
cp out.ttf /mnt/d/font/9_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 10
cp out.ttf /mnt/d/font/10_out.ttf
rm -rf svg
rm -rf svg_out
python3 GetFont.py 12
cp out.ttf /mnt/d/font/12_out.ttf

